# Challenge: Backtest on Other Datasets

## Download data from `yfinance`

In [134]:
import yfinance as yf

In [135]:
ticker = 'ETH-USD'
df_ETHUSD= yf.download(ticker, multi_level_index=False, auto_adjust=False)
df_ETHUSD

[*********************100%***********************]  1 of 1 completed

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2026-04-27,2303.063965,2303.063965,2403.726562,2267.409424,2369.841797,17879618684
2026-04-28,2289.419678,2289.419678,2310.442139,2259.057373,2303.079834,12761522276
2026-04-29,2253.415771,2253.415771,2345.939697,2221.223877,2289.412109,21884731493
2026-04-30,2256.251221,2256.251221,2277.718262,2232.130859,2253.484375,12309496389
2026-05-01,2295.093750,2295.093750,2324.788086,2256.078125,2256.344971,13243880777
2026-05-02,2316.231934,2316.231934,2339.743652,2292.722656,2295.044434,6905015549
2026-05-03,2321.635742,2321.635742,2354.710205,2297.553223,2316.210938,9861070993
2026-05-04,2346.396973,2346.396973,2397.608398,2309.260986,2321.816406,25497505008
2026-05-05,2361.182617,2361.182617,2398.833496,2344.934326,2346.415039,17739612383
2026-05-06,2350.802002,2350.802002,2423.040283,2338.483154,2361.290771,22745786496
2026-05-07,2291.107666,2291.107666,2351.738037,2280.814697,2350.852539,23409823896
2026-05-08,2306.972168,2306.972168,2320.692139,2265.833252,2291.075684,20013463010
2026-05-09,2326.727295,2326.727295,2336.927002,2300.544922,2307.069580,12217205123
2026-05-10,2369.043945,2369.043945,2381.263916,2313.127197,2326.744385,19587186882
2026-05-11,2339.360840,2339.360840,2374.303467,2305.080811,2369.193359,15525623296
2026-05-12,2274.643555,2274.643555,2339.690430,2256.419434,2339.287109,16145394773
2026-05-13,2257.576416,2257.576416,2322.233154,2233.553223,2274.591797,15193768365
2026-05-14,2280.934814,2280.934814,2317.948486,2238.471924,2257.571777,17563432027
2026-05-15,2223.328857,2223.328857,2298.686279,2204.765381,2280.933350,18146855938
2026-05-16,2179.751953,2179.751953,2229.845947,2162.048828,2223.338379,11451672017
2026-05-17,2127.645264,2127.645264,2196.782227,2097.020996,2179.854492,10143205921
2026-05-18,2128.516113,2128.516113,2155.964111,2078.616211,2127.681396,19890789125
2026-05-19,2109.963867,2109.963867,2143.562988,2093.475342,2128.531982,12030742868
2026-05-20,2126.983398,2126.983398,2146.506348,2101.833496,2109.854004,12076799234
2026-05-21,2131.410645,2131.410645,2154.222168,2103.460449,2127.172363,14344389472
2026-05-22,2064.636963,2064.636963,2138.979980,2056.929199,2131.370117,13229489284
2026-05-23,2115.951416,2115.951416,2145.579346,2010.550415,2064.634766,16650709488
2026-05-24,2097.993896,2097.993896,2127.309814,2061.329834,2115.544922,10602558120
2026-05-25,2111.370361,2111.370361,2138.411377,2090.516357,2097.993896,10167436482
2026-05-26,2070.858154,2070.858154,2138.006104,2054.361084,2111.366455,15924080901
2026-05-27,2083.149902,2083.149902,2091.126465,2058.411377,2071.070557,15754745856

## Preprocess the data

### Filter the date range

- Since 1 year ago at least

In [136]:
df_ETHUSD_yahoo = df_ETHUSD.loc['2024-05-26':,:].copy()

### Create the target variable

#### Percentage change

- Percentage change on `Adj Close` for tomorrow

In [137]:
df_ETHUSD_yahoo['change_tomorrow']= df_ETHUSD_yahoo.Close.pct_change(-1)* 100 * -1

#### Drop rows with any missing data

In [138]:
df_ETHUSD_yahoo= df_ETHUSD_yahoo.dropna().copy()

#### Change sign

Did the stock go up or down?

In [139]:
import numpy as np

In [140]:
df_ETHUSD_yahoo['change_tomorrow_direction']= np.where(df_ETHUSD_yahoo.change_tomorrow > 0 ,'UP','DOWN')

In [141]:
df_ETHUSD_yahoo

,Adj Close,Close,High,Low,Open,Volume,change_tomorrow,change_tomorrow_direction
Date,,,,,,,,
2026-04-27,2303.063965,2303.063965,2403.726562,2267.409424,2369.841797,17879618684,-0.595971,DOWN
2026-04-28,2289.419678,2289.419678,2310.442139,2259.057373,2303.079834,12761522276,-1.597748,DOWN
2026-04-29,2253.415771,2253.415771,2345.939697,2221.223877,2289.412109,21884731493,0.125671,UP
2026-04-30,2256.251221,2256.251221,2277.718262,2232.130859,2253.484375,12309496389,1.692416,UP
2026-05-01,2295.093750,2295.093750,2324.788086,2256.078125,2256.344971,13243880777,0.912611,UP
2026-05-02,2316.231934,2316.231934,2339.743652,2292.722656,2295.044434,6905015549,0.232759,UP
2026-05-03,2321.635742,2321.635742,2354.710205,2297.553223,2316.210938,9861070993,1.055287,UP
2026-05-04,2346.396973,2346.396973,2397.608398,2309.260986,2321.816406,25497505008,0.626197,UP
2026-05-05,2361.182617,2361.182617,2398.833496,2344.934326,2346.415039,17739612383,-0.441578,DOWN
2026-05-06,2350.802002,2350.802002,2423.040283,2338.483154,2361.290771,22745786496,-2.605479,DOWN
2026-05-07,2291.107666,2291.107666,2351.738037,2280.814697,2350.852539,23409823896,0.687676,UP
2026-05-08,2306.972168,2306.972168,2320.692139,2265.833252,2291.075684,20013463010,0.849052,UP
2026-05-09,2326.727295,2326.727295,2336.927002,2300.544922,2307.069580,12217205123,1.786233,UP
2026-05-10,2369.043945,2369.043945,2381.263916,2313.127197,2326.744385,19587186882,-1.268855,DOWN
2026-05-11,2339.360840,2339.360840,2374.303467,2305.080811,2369.193359,15525623296,-2.845162,DOWN
2026-05-12,2274.643555,2274.643555,2339.690430,2256.419434,2339.287109,16145394773,-0.755994,DOWN
2026-05-13,2257.576416,2257.576416,2322.233154,2233.553223,2274.591797,15193768365,1.024071,UP
2026-05-14,2280.934814,2280.934814,2317.948486,2238.471924,2257.571777,17563432027,-2.590978,DOWN
2026-05-15,2223.328857,2223.328857,2298.686279,2204.765381,2280.933350,18146855938,-1.999168,DOWN
2026-05-16,2179.751953,2179.751953,2229.845947,2162.048828,2223.338379,11451672017,-2.449031,DOWN
2026-05-17,2127.645264,2127.645264,2196.782227,2097.020996,2179.854492,10143205921,0.040913,UP
2026-05-18,2128.516113,2128.516113,2155.964111,2078.616211,2127.681396,19890789125,-0.879268,DOWN
2026-05-19,2109.963867,2109.963867,2143.562988,2093.475342,2128.531982,12030742868,0.800172,UP
2026-05-20,2126.983398,2126.983398,2146.506348,2101.833496,2109.854004,12076799234,0.207714,UP
2026-05-21,2131.410645,2131.410645,2154.222168,2103.460449,2127.172363,14344389472,-3.234161,DOWN
2026-05-22,2064.636963,2064.636963,2138.979980,2056.929199,2131.370117,13229489284,2.425124,UP
2026-05-23,2115.951416,2115.951416,2145.579346,2010.550415,2064.634766,16650709488,-0.855938,DOWN
2026-05-24,2097.993896,2097.993896,2127.309814,2061.329834,2115.544922,10602558120,0.633544,UP
2026-05-25,2111.370361,2111.370361,2138.411377,2090.516357,2097.993896,10167436482,-1.956300,DOWN
2026-05-26,2070.858154,2070.858154,2138.006104,2054.361084,2111.366455,15924080901,0.590056,UP

## Compute Machine Learning model

Proposal: Random Forest within `ensemble` module of `sklearn` library

In [142]:
from sklearn.ensemble import RandomForestClassifier

In [143]:
model = RandomForestClassifier(max_depth=7, random_state=42)

In [144]:
y = df_ETHUSD_yahoo.change_tomorrow_direction
X = df_ETHUSD_yahoo.drop(columns=['change_tomorrow', 'change_tomorrow_direction'])

In [145]:
target = df_ETHUSD_yahoo.change_tomorrow_direction

In [146]:
df_explanatory = df_ETHUSD_yahoo.drop(columns=['change_tomorrow', 'change_tomorrow_direction'])

In [147]:
model.fit(X, y)

RandomForestClassifier(max_depth=7, random_state=42)

## Backtesting

### Create the Strategy

In [148]:
from backtesting import Backtest, Strategy

In [149]:
explanatory_today= df_explanatory.iloc[[-1],:]

### Run the Backtest

In [150]:
import pandas as pd

In [153]:
class SimpleClassificationUD(Strategy):
    def init(self):
        self.model = model
        self.already_bought = False

    def next(self):
        explanatory_today = self.data.df.iloc[-1:, :]
        forecast_tomorrow = self.model.predict(explanatory_today)[0]
        
        # conditions to sell or buy
        if forecast_tomorrow == 1 and self.already_bought == False:
            self.buy()
            self.already_bought = True
        elif forecast_tomorrow == -1 and self.already_bought == True:
            self.sell()
            self.already_bought = False
        else:
            pass

In [154]:
bt = Backtest(
    X, SimpleClassificationUD, cash=10000,
    commission=.002, exclusive_orders=True
)

### Show the report in a DataFrame

In [155]:
bt.run()

stats = bt.run()
pd.DataFrame(stats).reset_index()

                     index                                                  0
0                    Start                                2026-04-27 00:00:00
1                      End                                2026-05-26 00:00:00
2                 Duration                                   29 days 00:00:00
3        Exposure Time [%]                                                0.0
4         Equity Final [$]                                            10000.0
5          Equity Peak [$]                                            10000.0
6               Return [%]                                                0.0
7    Buy & Hold Return [%]                                         -10.082473
8        Return (Ann.) [%]                                                0.0
9    Volatility (Ann.) [%]                                                0.0
10            Sharpe Ratio                                                NaN
11           Sortino Ratio                                                NaN
12            Calmar Ratio                                                NaN
13       Max. Drawdown [%]                                               -0.0
14       Avg. Drawdown [%]                                                NaN
15  Max. Drawdown Duration                                                NaN
16  Avg. Drawdown Duration                                                NaN
17                # Trades                                                  0
18            Win Rate [%]                                                NaN
19          Best Trade [%]                                                NaN
20         Worst Trade [%]                                                NaN
21          Avg. Trade [%]                                                NaN
22     Max. Trade Duration                                                NaN
23     Avg. Trade Duration                                                NaN
24           Profit Factor                                                NaN
25          Expectancy [%]                                                NaN
26                     SQN                                                NaN
27               _strategy                             SimpleClassificationUD
28           _equity_curve               Equity  DrawdownPct  DrawdownDura...
29                 _trades  Empty DataFrame
Columns: [Size, EntryBar, Exit...

## Plot the backtest report

> Don't worry about this new tool just yet, we will explain in a future chapter how to interpret the following chart.

In [156]:
bt.plot(filename='backtest_report.html', open_browser=False)

/Users/neemaurassa/Library/Python/3.9/lib/python/site-packages/backtesting/_plotting.py:250: UserWarning: DatetimeFormatter scales now only accept a single format. Using the first provided: '%d %b'
  formatter=DatetimeTickFormatter(days=['%d %b', '%a %d'],
/Users/neemaurassa/Library/Python/3.9/lib/python/site-packages/backtesting/_plotting.py:250: UserWarning: DatetimeFormatter scales now only accept a single format. Using the first provided: '%m/%Y'
  formatter=DatetimeTickFormatter(days=['%d %b', '%a %d'],
/Users/neemaurassa/Library/Python/3.9/lib/python/site-packages/backtesting/_plotting.py:455: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df2 = (df.assign(_width=1).set_index('datetime')
/Users/neemaurassa/Library/Python/3.9/lib/python/site-packages/backtesting/_plotting.py:659: UserWarning: found multiple competing values for 'toolbar.active_drag' property; using the latest value
  fig = gridplot(
/Users/neemaurassa/Library/Python/3.9/lib/python/site-packages/backtesting/_plotting.py:659: UserWarning: found multiple competing values for 'toolbar.active_scroll' property; using the latest value
  fig = gridplot(

GridPlot(id='p1155', ...)

## How to invest based on the numerical increase?

> Instead of the direction (UP or DOWN)

Next chapter → [Backtesting with Regression Models]()

Classification Model | Regression Model
-|-
![](src/pred_classification.png) | ![](src/pred_regression.png)

Classification Strategy | Regression Strategy
-|-
![](src/res_classification.png) | ![](src/res_regression.png)