# Backtesting ML Regression-Based

In [40]:
???

Object `?` not found.

Classification Strategy | Regression Strategy
-|-
![](src/res_classification.png) | ![](src/res_regression.png)

## Load the model

In [41]:
import pickle

In [42]:
with open('models/model_dt_regression.pkl','rb') as f:
    model_dt = pickle.load(f)

In [43]:
model_dt

DecisionTreeRegressor(max_depth=15)

## Load the data

In [44]:
import pandas as pd

df = pd.read_excel('data/Microsoft_LinkedIn_Processed.xlsx', index_col=0, parse_dates=['Date'])
df

,Close,High,Low,Open,Volume,change_tomorrow,change_tomorrow_direction
Date,,,,,,,
2016-12-08,61.009998,61.580002,60.840000,61.299999,21220800,1.549141,UP
2016-12-09,61.970001,61.990002,61.130001,61.180000,27349400,0.321694,UP
2016-12-12,62.169998,62.299999,61.720001,61.820000,20198100,1.286125,UP
2016-12-13,62.980000,63.419998,62.240002,62.500000,35718900,-0.478620,DOWN
2016-12-14,62.680000,63.450001,62.529999,63.000000,30352700,-0.159793,DOWN
...,...,...,...,...,...,...,...
2026-05-14,409.429993,411.839996,400.880005,404.480011,27077500,2.960282,UP
2026-05-15,421.920013,428.170013,412.910004,414.269989,50771200,0.382489,UP
2026-05-18,423.540009,425.119995,415.609985,416.619995,32564100,-1.466148,DOWN
2026-05-19,417.420013,432.700012,416.489990,429.899994,33018700,0.864481,UP
2026-05-20,421.059998,422.100006,411.299988,414.170013,27864000,-0.470066,DOWN

## Backtesting.py Library

### Create your Strategy Class

In [45]:
from backtesting import Backtest, Strategy

In [66]:
class Regression(Strategy):
    def init(self):
        self.model = model_dt
        self.already_bought = False

    def next(self):
        explanatory_today = pd.DataFrame([self.data.df.iloc[-1]])
        explanatory_today = explanatory_today[model_dt.feature_names_in_]  # align columns
        forecast_tomorrow = model_dt.predict(explanatory_today)[0]
        
        # conditions to buy or sell
        if forecast_tomorrow > 1 and self.already_bought == False:
            self.buy
            self.already_bought == True 
        elif forecast_tomorrow < -5 and self.already_bought == True:
            self.sell
            self.already_bought == False
        else:
            pass

### Define initial conditions

In [67]:
df_explanatory = df.drop(columns=['change_tomorrow','change_tomorrow_direction'])

In [68]:
bt = Backtest(df_explanatory, Regression,
              cash=10000, commission=.002, exclusive_orders=True)

### Run backtesting

In [69]:
results = bt.run()

### Interpret backtesting results

In [70]:
results.to_frame(name='Values').loc[:'Return [%]']

                                Values
Start              2016-12-08 00:00:00
End                2026-05-20 00:00:00
Duration            3450 days 00:00:00
Exposure Time [%]                  0.0
Equity Final [$]               10000.0
Equity Peak [$]                10000.0
Return [%]                         0.0

### Visualize the strategy performance

In [71]:
bt.plot(filename='reports_backtesting/classification.html')

BokehDeprecationWarning: Passing lists of formats for DatetimeTickFormatter scales was deprecated in Bokeh 3.0. Configure a single string format for each scale
/Users/neemaurassa/Library/Python/3.9/lib/python/site-packages/backtesting/_plotting.py:250: UserWarning: DatetimeFormatter scales now only accept a single format. Using the first provided: '%d %b'
  formatter=DatetimeTickFormatter(days=['%d %b', '%a %d'],
BokehDeprecationWarning: Passing lists of formats for DatetimeTickFormatter scales was deprecated in Bokeh 3.0. Configure a single string format for each scale
/Users/neemaurassa/Library/Python/3.9/lib/python/site-packages/backtesting/_plotting.py:250: UserWarning: DatetimeFormatter scales now only accept a single format. Using the first provided: '%m/%Y'
  formatter=DatetimeTickFormatter(days=['%d %b', '%a %d'],
/Users/neemaurassa/Library/Python/3.9/lib/python/site-packages/backtesting/_plotting.py:455: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df2 = (df.assign(_width=1).set_index('datetime')
/Users/neemaurassa/Library/Python/3.9/lib/python/site-packages/backtesting/_plotting.py:659: UserWarning: found multiple competing values for 'toolbar.active_drag' property; using the latest value
  fig = gridplot(
/Users/neemaurassa/Library/Python/3.9/lib/python/site-packages/backtesting/_plotting.py:659: UserWarning: found multiple competing values for 'toolbar.active_scroll' property; using the latest value
  fig = gridplot(

GridPlot(id='p1687', ...)